# Generated by Django 2.2.12 on 2020-08-02 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judge', '0110_auto_20200802_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_into', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='peg_merge_into', to='judge.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='peg_user', to='judge.Profile')),
            ],
        ),
    ]
