# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0018_django_1_9'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.CharField(default=b'', help_text='', max_length=150, verbose_name=b'OpenGraph image'),
        ),
        migrations.AddField(
            model_name='contest',
            name='og_image',
            field=models.CharField(default=b'', help_text='', max_length=150, verbose_name=b'OpenGraph image'),
        ),
    ]
