# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 06:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0020_profile_user_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='output_prefix_override',
            field=models.IntegerField(help_text='', null=True, verbose_name='Output prefix length override'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_image',
            field=models.CharField(blank=True, default=b'', help_text='', max_length=150, verbose_name='OpenGraph image'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='judge.Comment', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_rated',
            field=models.BooleanField(default=False, help_text='Whether this contest can be rated.', verbose_name='Contest rated'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='og_image',
            field=models.CharField(blank=True, default=b'', help_text='', max_length=150, verbose_name='OpenGraph image'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='If private, only these organizations may see the contest', to='judge.Organization', verbose_name='Organizations'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='rate_all',
            field=models.BooleanField(default=False, help_text='Rate all users who joined.', verbose_name='Rate all'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='rate_exclude',
            field=models.ManyToManyField(blank=True, help_text='', related_name='_contest_rate_exclude_+', to='judge.Profile', verbose_name='Exclude from ratings'),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='contest',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='judge.Contest', verbose_name='Contest'),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, help_text='', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='partial',
            field=models.BooleanField(default=True, help_text='', verbose_name='Partial'),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='points',
            field=models.IntegerField(help_text='', verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='contestproblem',
            name='problem',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, related_name='contests', to='judge.Problem', verbose_name='Problem'),
        ),
        migrations.AlterField(
            model_name='contestsubmission',
            name='participation',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', related_query_name=b'submission', to='judge.ContestParticipation', verbose_name='Participation'),
        ),
        migrations.AlterField(
            model_name='contestsubmission',
            name='points',
            field=models.FloatField(default=0.0, help_text='', verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='contestsubmission',
            name='problem',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', related_query_name=b'submission', to='judge.ContestProblem', verbose_name='Problem'),
        ),
        migrations.AlterField(
            model_name='contestsubmission',
            name='submission',
            field=models.OneToOneField(help_text='', on_delete=django.db.models.deletion.CASCADE, related_name='contest', to='judge.Submission', verbose_name='Submission'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='', verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='description',
            field=models.TextField(blank=True, help_text='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='problems',
            field=models.ManyToManyField(help_text='', related_name='judges', to='judge.Problem', verbose_name='Problems'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='runtimes',
            field=models.ManyToManyField(help_text='', related_name='judges', to='judge.Language', verbose_name='Judges'),
        ),
        migrations.AlterField(
            model_name='language',
            name='extension',
            field=models.CharField(help_text='', max_length=10, verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='languagelimit',
            name='language',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, to='judge.Language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='languagelimit',
            name='memory_limit',
            field=models.IntegerField(help_text='', verbose_name='Memory limit'),
        ),
        migrations.AlterField(
            model_name='languagelimit',
            name='problem',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, related_name='language_limits', to='judge.Problem', verbose_name='Problem'),
        ),
        migrations.AlterField(
            model_name='languagelimit',
            name='time_limit',
            field=models.FloatField(help_text='', verbose_name='Time limit'),
        ),
        migrations.AlterField(
            model_name='license',
            name='display',
            field=models.CharField(blank=True, help_text='Displayed on pages under this license', max_length=256, verbose_name='Short name'),
        ),
        migrations.AlterField(
            model_name='license',
            name='icon',
            field=models.CharField(blank=True, help_text='URL to the icon', max_length=256, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='license',
            name='key',
            field=models.CharField(help_text='', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(b'^[-\\w.]+$', b'License key must be ^[-\\w.]+$')], verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='license',
            name='link',
            field=models.CharField(help_text='', max_length=256, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(help_text='', max_length=256, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='navigationbar',
            name='label',
            field=models.CharField(help_text='', max_length=20, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='navigationbar',
            name='order',
            field=models.PositiveIntegerField(db_index=True, help_text='', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='organizationrequest',
            name='organization',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='judge.Organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='organizationrequest',
            name='reason',
            field=models.TextField(help_text='', verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='organizationrequest',
            name='state',
            field=models.CharField(choices=[(b'P', b'Pending'), (b'A', b'Approved'), (b'R', b'Rejected')], help_text='', max_length=1, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='organizationrequest',
            name='user',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='judge.Profile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_rank',
            field=models.CharField(choices=[(b'user', b'Normal User'), (b'setter', b'Problem Setter'), (b'admin', b'Admin')], default=b'user', help_text='', max_length=10, verbose_name='Display rank'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='contest',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='judge.Contest', verbose_name='Contest'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='last_rated',
            field=models.DateTimeField(db_index=True, help_text='', verbose_name='Last rated'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='participation',
            field=models.OneToOneField(help_text='', on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='judge.ContestParticipation', verbose_name='Participation'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rank',
            field=models.IntegerField(help_text='', verbose_name='Rank'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(help_text='', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='judge.Profile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='volatility',
            field=models.IntegerField(help_text='', verbose_name='Volatility'),
        ),
    ]
