# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0021_output_prefix_override'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judge',
            options={'ordering': ['load']},
        ),
        migrations.RemoveField(
            model_name='judge',
            name='online',
        ),
        migrations.RenameField(
            model_name='judge',
            old_name='last_connect',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='judge',
            name='last_ping',
            field=models.DateTimeField(null=True, verbose_name='Last ping time'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='Judge start time'),
        ),
    ]
