# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 01:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0022_judge_last_ping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='tag name')),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(b'^#(?:[A-Fa-f0-9]{3}){1,2}$', 'Invalid colour.')], verbose_name='tag colour')),
                ('description', models.TextField(blank=True, verbose_name='tag description')),
            ],
            options={
                'verbose_name': 'contest tag',
                'verbose_name_plural': 'contest tags',
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': (('see_hidden_post', 'See hidden posts'),), 'verbose_name': 'blog post', 'verbose_name_plural': 'blog posts'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='commentvote',
            options={'verbose_name': 'comment vote', 'verbose_name_plural': 'comment votes'},
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('see_private_contest', 'See private contests'), ('edit_own_contest', 'Edit own contests'), ('edit_all_contest', 'Edit all contests'), ('contest_rating', 'Rate contests')), 'verbose_name': 'contest', 'verbose_name_plural': 'contests'},
        ),
        migrations.AlterModelOptions(
            name='contestparticipation',
            options={'verbose_name': 'contest participation', 'verbose_name_plural': 'contest participations'},
        ),
        migrations.AlterModelOptions(
            name='contestproblem',
            options={'verbose_name': 'contest problem', 'verbose_name_plural': 'contest problems'},
        ),
        migrations.AlterModelOptions(
            name='contestprofile',
            options={'verbose_name': 'contest profile', 'verbose_name_plural': 'contest profiles'},
        ),
        migrations.AlterModelOptions(
            name='contestsubmission',
            options={'verbose_name': 'contest submission', 'verbose_name_plural': 'contest submissions'},
        ),
        migrations.AlterModelOptions(
            name='judge',
            options={'ordering': ['name'], 'verbose_name': 'judge', 'verbose_name_plural': 'judges'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['key'], 'verbose_name': 'language', 'verbose_name_plural': 'languages'},
        ),
        migrations.AlterModelOptions(
            name='languagelimit',
            options={'verbose_name': 'language-specific resource limit', 'verbose_name_plural': 'language-specific resource limits'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'license', 'verbose_name_plural': 'licenses'},
        ),
        migrations.AlterModelOptions(
            name='miscconfig',
            options={'verbose_name': 'configuration item', 'verbose_name_plural': 'miscellaneous configuration'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['key'], 'permissions': (('organization_admin', 'Administer organizations'), ('edit_all_organization', 'Edit all organizations')), 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='organizationrequest',
            options={'verbose_name': 'organization join request', 'verbose_name_plural': 'organization join requests'},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('see_private_problem', 'See hidden problems'), ('edit_own_problem', 'Edit own problems'), ('edit_all_problem', 'Edit all problems'), ('edit_public_problem', 'Edit all public problems'), ('clone_problem', 'Clone problem')), 'verbose_name': 'problem', 'verbose_name_plural': 'problems'},
        ),
        migrations.AlterModelOptions(
            name='problemgroup',
            options={'ordering': ['full_name'], 'verbose_name': 'problem group', 'verbose_name_plural': 'problem groups'},
        ),
        migrations.AlterModelOptions(
            name='problemtype',
            options={'ordering': ['full_name'], 'verbose_name': 'problem type', 'verbose_name_plural': 'problem types'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('test_site', 'Shows in-progress development stuff'),), 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'contest rating', 'verbose_name_plural': 'contest ratings'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'permissions': (('see_private_solution', 'See hidden solutions'),), 'verbose_name': 'solution', 'verbose_name_plural': 'solutions'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'permissions': (('abort_any_submission', 'Abort any submission'), ('rejudge_submission', 'Rejudge the submission'), ('rejudge_submission_lot', 'Rejudge a lot of submissions'), ('spam_submission', 'Submit without limit'), ('view_all_submission', 'View all submission'), ('resubmit_other', "Resubmit others' submission")), 'verbose_name': 'submission', 'verbose_name_plural': 'submissions'},
        ),
        migrations.AlterModelOptions(
            name='submissiontestcase',
            options={'verbose_name': 'submission test case', 'verbose_name_plural': 'submission test cases'},
        ),
        migrations.AddField(
            model_name='contest',
            name='tags',
            field=models.ManyToManyField(blank=True, to='judge.ContestTag', verbose_name='contest tags', related_name='contests'),
        ),
    ]
