# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0027_bridge_revert'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name=b'Last connected IP'),
        ),
    ]
