# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0028_judge_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'de', 'German'), (b'en', 'English'), (b'fr', 'French'), (b'ro', 'Romanian'), (b'ru', 'Russian'), (b'zh-hans', 'Simplified Chinese')], max_length=7, verbose_name='language')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='translated name')),
                ('description', models.TextField(verbose_name='translated description')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='judge.Problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'problem translation',
                'verbose_name_plural': 'problem translations',
            },
        ),
        migrations.AlterUniqueTogether(
            name='problemtranslation',
            unique_together=set([('problem', 'language')]),
        ),
    ]
