# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0033_proper_pretest_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_pretested',
            field=models.BooleanField(default=False, help_text='', verbose_name='was ran on pretests only'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='error',
            field=models.TextField(blank=True, help_text='', null=True, verbose_name='compile errors'),
        ),
    ]
