# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0035_contest_spectate_mode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestparticipation',
            unique_together=set([('contest', 'user')]),
        ),
    ]
