# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0036_contest_participation_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='ac_rate',
            field=models.FloatField(default=0, verbose_name='rate of AC submissions'),
        ),
        migrations.AddField(
            model_name='problem',
            name='user_count',
            field=models.IntegerField(default=0, help_text='The amount of users on the best solutions page.', verbose_name='amount of users'),
        ),
    ]
