# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0037_user_count_ac_rate_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='problem_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
