# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0038_profile_problem_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='is_external',
        ),
    ]
