# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0040_profile_math_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='virtual',
            field=models.IntegerField(default=0, help_text='0 means non-virtual, otherwise the n-th virtual participation', verbose_name='virtual participation id'),
        ),
        migrations.AlterUniqueTogether(
            name='contestparticipation',
            unique_together=set([('contest', 'user', 'virtual')]),
        ),
    ]
