# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 22:21
from __future__ import unicode_literals

from django.db import migrations, models


def add_contest_user_count(apps, schema_editor):
    Contest = apps.get_model('judge', 'Contest')
    for contest in Contest.objects.using(schema_editor.connection.alias):
        contest.user_count = contest.users.filter(virtual=0).count()
        contest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0042_remove_spectate_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='user_count',
            field=models.IntegerField(default=0, verbose_name='the amount of live participants'),
        ),
        migrations.RunPython(add_contest_user_count, migrations.RunPython.noop),
    ]
