# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0043_contest_user_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slots',
            field=models.IntegerField(help_text='Maximum amount of users in this organization, only applicable to private organizations', null=True, verbose_name='maximum size'),
        ),
    ]
