# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0048_site_managed_checkers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='summary',
            field=models.TextField(blank=True, help_text='Plain-text, shown in meta description tag, e.g. for social media.', verbose_name='contest summary'),
        ),
    ]
