# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0050_problem_tester_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='is_being_rejudged',
            new_name='was_rejudged',
        ),
        migrations.AlterField(
            model_name='submission',
            name='was_rejudged',
            field=models.BooleanField(default=False, verbose_name='was rejudged by admin'),
        ),
        migrations.AlterField(
            model_name='problemtranslation',
            name='language',
            field=models.CharField(choices=[(b'de', 'German'), (b'en', 'English'), (b'fr', 'French'), (b'ro', 'Romanian'), (b'ru', 'Russian'), (b'sr-latn', 'Serbian (Latin)'), (b'zh-hans', 'Simplified Chinese')], max_length=7, verbose_name='language'),
        ),
    ]
