# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models


def contest_to_time_limit2(apps, schema_editor):
    Contest = apps.get_model('judge', 'Contest')
    db_alias = schema_editor.connection.alias
    for contest in Contest.objects.using(db_alias):
        contest.time_limit2 = contest.time_limit
        contest.save()


def contest_from_time_limit2(apps, schema_editor):
    Contest = apps.get_model('judge', 'Contest')
    db_alias = schema_editor.connection.alias
    for contest in Contest.objects.using(db_alias):
        contest.time_limit = contest.time_limit2
        contest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0051_was_rejudged_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='time_limit2',
            field=models.DurationField(blank=True, null=True, verbose_name='time limit'),
        ),
        migrations.RunPython(contest_to_time_limit2, contest_from_time_limit2),
        migrations.RemoveField(
            model_name='contest',
            name='time_limit',
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='time_limit2',
            new_name='time_limit',
        )
    ]
