# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0052_switch_to_durationfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='og_image',
            field=models.CharField(blank=True, max_length=150, verbose_name='OpenGraph image'),
        ),
        migrations.AddField(
            model_name='problem',
            name='summary',
            field=models.TextField(blank=True, help_text='Plain-text, shown in meta description tag, e.g. for social media.', verbose_name='problem summary'),
        ),
    ]
