# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 03:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('judge', '0053_opengraph_problems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='ticket title')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('notes', models.TextField(blank=True, help_text='Staff notes for this issue to aid in processing.', verbose_name='quick notes')),
                ('object_id', models.PositiveIntegerField(verbose_name='linked item ID')),
                ('assignees', models.ManyToManyField(to='judge.Profile', verbose_name='assignees')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='linked item type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='judge.Profile', verbose_name='ticket creator')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='message body')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='message time')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', related_query_name='message', to='judge.Ticket', verbose_name='ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to='judge.Profile', verbose_name='poster')),
            ],
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(db_index=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(db_index=True, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Allow joining organization', verbose_name='is open organization?'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='result',
            field=models.CharField(blank=True, choices=[(b'AC', 'Accepted'), (b'WA', 'Wrong Answer'), (b'TLE', 'Time Limit Exceeded'), (b'MLE', 'Memory Limit Exceeded'), (b'OLE', 'Output Limit Exceeded'), (b'IR', 'Invalid Return'), (b'RTE', 'Runtime Error'), (b'CE', 'Compile Error'), (b'IE', 'Internal Error'), (b'SC', 'Short circuit'), (b'AB', 'Aborted')], db_index=True, default=None, max_length=3, null=True, verbose_name='result'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[(b'QU', 'Queued'), (b'P', 'Processing'), (b'G', 'Grading'), (b'D', 'Completed'), (b'IE', 'Internal Error'), (b'CE', 'Compile Error'), (b'AB', 'Aborted')], db_index=True, default=b'QU', max_length=2, verbose_name='status'),
        ),
    ]
