# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-20 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0053_opengraph_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pp',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
