# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-22 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0054_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='performance_points',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
