# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-22 18:30
from __future__ import unicode_literals
from operator import mul

from django.db import migrations, models
from django.conf import settings

def gen_pp(apps, schema_editor):
    Profile = apps.get_model('judge', 'Profile')
    Submission = apps.get_model('judge', 'Submission')
    table = (lambda x: [pow(x,i) for i in xrange(100)])(getattr(settings, 'PP_STEP', 0.95))
    for row in Profile.objects.all():
        qdata = (Submission.objects.filter(user=row, points__isnull=False, problem__is_public=True)
                 .values('problem_id').distinct().annotate(points=models.Max('points')).order_by('-points')
                 .values_list('points', flat=True))
        row.performance_points = sum(map(mul, table[:min(len(qdata), len(table))], qdata[:min(len(qdata), len(table))]))
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0054_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='performance_points',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.RunPython(gen_pp, reverse_code=migrations.RunPython.noop),
    ]
