# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0058_problem_curator_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_points',
            field=models.BooleanField(default=False, help_text='User submissions will not receive any points.', verbose_name='no points for submissions'),
        ),
    ]
