# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0059_problem_is_manually_managed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemClarification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='clarification body')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='clarification timestamp')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='use_clarifications',
            field=models.BooleanField(default=True, help_text='Use clarification system instead of comments.', verbose_name='no comments'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='is_manually_managed',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether judges should be allowed to manage data or not', verbose_name='manually managed'),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='type',
            field=models.CharField(choices=[(b'C', 'Normal case'), (b'S', 'Batch start'), (b'E', 'Batch end')], default=b'C', max_length=1, verbose_name='case type'),
        ),
        migrations.AddField(
            model_name='problemclarification',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem', verbose_name='clarified problem'),
        ),
    ]
