# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 04:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0061_language_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='max_submissions',
            field=models.IntegerField(default=0, help_text='Maximum number of submissions for this problem, or 0 for no limit.', validators=[django.core.validators.MinValueValidator(0, "Why include a problem you can't submit to?")]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='title of comment'),
        ),
    ]
