# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0063_new_solutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='problem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.Problem', verbose_name='associated problem'),
        ),
    ]
