# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0068_hide_scoreboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='time_penalty_incorrect_solution',
            field=models.DurationField(blank=True, help_text='Time penalty for an incorrect solution.', null=True, verbose_name='time penalty'),
        ),
        migrations.AddField(
            model_name='contest',
            name='time_penalty_is_strict',
            field=models.BooleanField(default=False, help_text='Whether Compilation Error should count as an incorrect solution.', verbose_name='strict time penalty'),
        ),
        migrations.AlterField(
            model_name='problemtranslation',
            name='language',
            field=models.CharField(choices=[(b'de', 'German'), (b'en', 'English'), (b'es', 'Spanish'), (b'fr', 'French'), (b'hr', 'Croatian'), (b'hu', 'Hungarian'), (b'ko', 'Korean'), (b'ro', 'Romanian'), (b'ru', 'Russian'), (b'sr-latn', 'Serbian (Latin)'), (b'tr', 'Turkish'), (b'vi', 'Vietnamese'), (b'zh-hans', 'Simplified Chinese')], max_length=7, verbose_name='language'),
        ),
    ]
