# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0068_hide_scoreboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='time_bonus',
            field=models.IntegerField(default=0, help_text='Number of minutes to award an extra point for submitting before the contest end. Leave as 0 for no time bonus.', verbose_name='time bonus'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='time_bonus',
            field=models.IntegerField(default=0, verbose_name='time bonus'),
        ),
    ]
