# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0068_hide_scoreboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Whether this judge should be blocked from connecting, even if its key is correct.', verbose_name='block judge'),
        ),
        migrations.AlterField(
            model_name='problemtranslation',
            name='language',
            field=models.CharField(choices=[(b'de', 'German'), (b'en', 'English'), (b'es', 'Spanish'), (b'fr', 'French'), (b'hr', 'Croatian'), (b'hu', 'Hungarian'), (b'ko', 'Korean'), (b'ro', 'Romanian'), (b'ru', 'Russian'), (b'sr-latn', 'Serbian (Latin)'), (b'tr', 'Turkish'), (b'vi', 'Vietnamese'), (b'zh-hans', 'Simplified Chinese')], max_length=7, verbose_name='language'),
        ),
    ]
