# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-28 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0069_auto_20180603_0049'),
        ('judge', '0069_judge_blocking'),
    ]

    operations = [
    ]
