# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0069_judge_blocking'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_organization_private',
            field=models.BooleanField(default=False, verbose_name='private to organizations'),
        ),
        migrations.AddField(
            model_name='problem',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='If private, only these organizations may see the problem', to='judge.Organization', verbose_name='organizations'),
        ),
    ]
