# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0070_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='logo_override_image',
            field=models.CharField(blank=True, default=b'', help_text='This image will replace the default site logo for users inside the contest.', max_length=150, verbose_name='Logo override image'),
        ),
    ]
