# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-28 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0070_merge_20180928_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_rank',
            field=models.CharField(choices=[(b'user', b'Normal User'), (b'setter', b'Problem Setter'), (b'teacher', b'Teacher'), (b'admin', b'Admin')], default=b'user', max_length=10, verbose_name='display rank'),
        ),
    ]
