# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0072_contest_logo_override_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
