# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-20 19:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0073_comment_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_totp_enabled',
            field=models.BooleanField(default=False, help_text='check to enable TOTP-based two factor authentication', verbose_name='2FA enabled'),
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_key',
            field=judge.models.profile.EncryptedNullCharField(blank=True, help_text='32 character base32-encoded key for TOTP', max_length=32, null=True, validators=[django.core.validators.RegexValidator(b'^$|^[A-Z2-7]{32}$', 'TOTP key must be empty or base32')], verbose_name='TOTP key'),
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('test_site', 'Shows in-progress development stuff'), ('totp', 'Edit TOTP settings')), 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
    ]
