# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-06 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0072_contest_logo_override_image'),
        ('judge', '0073_auto_20181006_2149'),
    ]

    operations = [
    ]
