# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-13 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0074_merge_20181006_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsubmission',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='bonus'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='If private, only these organizations may see the problem.', to='judge.Organization', verbose_name='organizations'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_rank',
            field=models.CharField(choices=[(b'user', b'Normal User'), (b'setter', b'Problem Setter'), (b'exec', b'Exec'), (b'teacher', b'Teacher'), (b'admin', b'Admin')], default=b'user', max_length=10, verbose_name='display rank'),
        ),
    ]
