# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-15 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0075_auto_20181013_1608'),
        ('judge', '0075_organization_admin_reverse'),
    ]

    operations = [
    ]
