# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-27 21:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0076_merge_20181115_0337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('see_private_problem', 'See hidden problems'), ('see_restricted_problem', 'See restricted problems'), ('edit_own_problem', 'Edit own problems'), ('edit_all_problem', 'Edit all problems'), ('edit_public_problem', 'Edit all public problems'), ('clone_problem', 'Clone problem'), ('change_public_visibility', 'Change is_public field'), ('change_restricted_field', 'Change is_restricted field'), ('change_manually_managed', 'Change is_manually_managed field'), ('see_organization_problem', 'See organization-private problems')), 'verbose_name': 'problem', 'verbose_name_plural': 'problems'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('test_site', 'Shows in-progress development stuff'), ('totp', 'Edit TOTP settings'), ('view_name', "View user's real name")), 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_contest_account',
            field=models.BooleanField(default=False, help_text='If set, restricts this account to only contest features.', verbose_name='Contest account'),
        ),
        migrations.AlterField(
            model_name='commentlock',
            name='page',
            field=models.CharField(db_index=True, help_text='c:contest_code, p:problem_code, s:problem_solution_id, or b:blog_id', max_length=30, validators=[django.core.validators.RegexValidator(b'^[pcs]:[a-z0-9]+$|^b:\\d+$', 'Page code must be ^[pcs]:[a-z0-9]+$|^b:\\d+$')], verbose_name='associated page'),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_restricted',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether to restrict access to the problem, and require special permissions. Set for contest problems, such as LCC problems.', verbose_name='restricted'),
        ),
    ]
