# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-27 21:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0077_restricted_users_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_token',
            field=judge.models.profile.EncryptedNullCharField(blank=True, help_text='32 character base32-encoded key for API access', max_length=32, null=True, validators=[django.core.validators.RegexValidator(b'^$|^[A-Z2-7]{32}$', 'API token must be empty or base32')], verbose_name='API token'),
        ),
    ]
