# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-02 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0077_remove_organization_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='banned_users',
            field=models.ManyToManyField(blank=True, help_text='Bans the selected users from joining this contest', to='judge.Profile', verbose_name='personae non gratae'),
        ),
    ]
