# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-03 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0078_add_user_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
