# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-01 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0078_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_private_viewable',
            field=models.BooleanField(default=False, help_text='Whether only specified organizations can join the contest, but everyone can view.', verbose_name='viewable but private to organizations'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Whether only specified organizations can view and join this contest.', verbose_name='completely private to organizations'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='If private, only these organizations may join the contest', to='judge.Organization', verbose_name='organizations'),
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('see_private_contest', 'See private contests'), ('join_all_contest', 'Join all contests'), ('edit_own_contest', 'Edit own contests'), ('edit_all_contest', 'Edit all contests'), ('contest_rating', 'Rate contests'), ('contest_access_code', 'Contest access codes')), 'verbose_name': 'contest', 'verbose_name_plural': 'contests'},
        ),
        migrations.AddField(
            model_name='contest',
            name='is_virtualable',
            field=models.BooleanField(default=True, help_text='Whether a user can virtually participate in this contest or not.', verbose_name='virtualable'),
        ),
    ]
