# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-02 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0079_contest_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time of registration')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrants', to='judge.Contest', verbose_name='associated contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_registrations', to='judge.Profile', verbose_name='registrant')),
            ],
            options={
                'verbose_name': 'contest registration',
                'verbose_name_plural': 'contest registrations',
            },
        ),
        migrations.AlterUniqueTogether(
            name='contestregistration',
            unique_together=set([('contest', 'user')]),
        ),
        migrations.AddField(
            model_name='contest',
            name='require_registration',
            field=models.BooleanField(default=False, help_text='Whether the user must be registered before being able to join the contest', verbose_name='require registration'),
        ),
    ]
