# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-04 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0076_problem_statistics'),
        ('judge', '0080_contest_registration'),
    ]

    operations = [
    ]
