# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-05 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0080_contest_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='freeze_submissions',
            field=models.BooleanField(default=False, help_text='Whether submission updates should be frozen. If frozen, rejudging/rescoring will not propagate to related contest submissions until after this is unchecked.', verbose_name='freeze submissions'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='updated_frozen',
            field=models.BooleanField(default=False, help_text='Whether this submission was rejudged/rescored while the contest was frozen.', verbose_name='updated while frozen'),
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('see_private_contest', 'See private contests'), ('join_all_contest', 'Join all contests'), ('edit_own_contest', 'Edit own contests'), ('edit_all_contest', 'Edit all contests'), ('contest_frozen_state', 'Change contest frozen state'), ('contest_rating', 'Rate contests'), ('contest_access_code', 'Contest access codes')), 'verbose_name': 'contest', 'verbose_name_plural': 'contests'},
        ),
    ]
