# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-24 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0081_contest_freeze'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('see_private_contest', 'See private contests'), ('join_all_contest', 'Join all contests'), ('edit_own_contest', 'Edit own contests'), ('edit_all_contest', 'Edit all contests'), ('clone_contest', 'Clone contest'), ('contest_frozen_state', 'Change contest frozen state'), ('contest_rating', 'Rate contests'), ('contest_access_code', 'Contest access codes')), 'verbose_name': 'contest', 'verbose_name_plural': 'contests'},
        ),
    ]
