# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-01 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0082_contest_clone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_rank',
            field=models.CharField(choices=[(b'user', b'Normal User'), (b'exec', b'Exec'), (b'president', b'President'), (b'alumnus', b'Alumnus'), (b'setter', b'Problem Setter'), (b'teacher', b'Teacher'), (b'admin', b'Admin')], default=b'user', max_length=10, verbose_name='display rank'),
        ),
    ]
