# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-15 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0082_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontestcase',
            name='extended_feedback',
            field=models.TextField(blank=True, verbose_name='extended judging feedback'),
        ),
    ]
