# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-24 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0083_add_display_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_organization_private',
            field=models.BooleanField(default=False, verbose_name='private to organizations'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='If private, only these organizations may see the blog post.', to='judge.Organization', verbose_name='organizations'),
        ),
    ]
