# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-11 07:29
from __future__ import unicode_literals, print_function

from django.db import migrations, models
import jsonfield.fields

from judge.contest_format.default import DefaultContestFormat


def contest_format_config(apps, schema_editor):
    Contest = apps.get_model('judge', 'Contest')
    db_alias = schema_editor.connection.alias

    def get_start(self):
        contest = self.contest
        return contest.start_time if contest.time_limit is None and not self.virtual > 0 else self.real_start

    contests = Contest.objects.using(db_alias)
    print('Updating %d contests:' % len(contests))

    for contest in contests:
        participations = contest.users.all()
        print('Updating contest %s (%d participations): %s' % (contest.key, len(participations), contest.name))

        format = DefaultContestFormat(contest, None)
        for participation in participations:
            participation.start = get_start(participation)
            format.update_participation(participation)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0083_extended_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='format_config',
            field=jsonfield.fields.JSONField(blank=True, help_text='A JSON object to serve as the configuration for the chosen contest format module. Leave empty to use None. Exact format depends on the contest format selected.', null=True, verbose_name='contest format configuration'),
        ),
        migrations.AddField(
            model_name='contest',
            name='format_name',
            field=models.CharField(choices=[(b'default', 'Default')], default=b'default', help_text='The contest format module to use.', max_length=32, verbose_name='contest format'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='format_data',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='contest format specific data'),
        ),
        migrations.RunPython(contest_format_config, migrations.RunPython.noop),
    ]
