# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-13 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0077_remove_organization_key'),
        ('judge', '0083_add_user_notes'),
    ]

    operations = [
    ]
