# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-03 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0079_remove_comment_title'),
        ('judge', '0083_add_display_ranks'),
    ]

    operations = [
    ]
