# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-15 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0084_extended_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('see_private_contest', 'See private contests'), ('edit_own_contest', 'Edit own contests'), ('edit_all_contest', 'Edit all contests'), ('contest_frozen_state', 'Change contest frozen state'), ('contest_rating', 'Rate contests'), ('contest_access_code', 'Contest access codes')), 'verbose_name': 'contest', 'verbose_name_plural': 'contests'},
        ),
        migrations.AddField(
            model_name='contest',
            name='freeze_submissions',
            field=models.BooleanField(default=False, help_text='Whether submission updates should be frozen. If frozen, rejudging/rescoring will not propagate to related contest submissions until after this is unchecked.', verbose_name='freeze submissions'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='updated_frozen',
            field=models.BooleanField(default=False, help_text='Whether this submission was rejudged/rescored while the contest was frozen.', verbose_name='updated while frozen'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='format_name',
            field=models.CharField(choices=[(b'default', 'Default'), (b'ecoo', 'ECOO')], default=b'default', help_text='The contest format module to use.', max_length=32, verbose_name='contest format'),
        ),
    ]
