# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-01 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0081_unlisted_users'),
        ('judge', '0085_contest_registration_data'),
    ]

    operations = [
    ]
