# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-17 01:14
from __future__ import unicode_literals, print_function

from django.db import migrations, models
import jsonfield.fields

from judge.contest_format.bonuses import BonusesContestFormat
from judge.contest_format.default import DefaultContestFormat


def contest_format_config(apps, schema_editor):
    Contest = apps.get_model('judge', 'Contest')
    db_alias = schema_editor.connection.alias

    def get_start(self):
        contest = self.contest
        return contest.start_time if contest.time_limit is None and not self.virtual > 0 else self.real_start

    contests = Contest.objects.using(db_alias)
    print('Updating %d contests:' % len(contests))

    for contest in contests:
        participations = contest.users.all()
        print('Updating contest %s (%d participations): %s' % (contest.key, len(participations), contest.name))

        has_bonus = contest.time_bonus or contest.first_submission_bonus
        if has_bonus:
            print('Contest has bonuses, using the bonuses contest format.')
            contest.format_name = 'bonuses'
            contest.format_config = {'time_bonus': contest.time_bonus, 'first_submission_bonus': contest.first_submission_bonus}
            contest.save()
            format = BonusesContestFormat(contest, contest.format_config)
        else:
            print('Contest does not have bonuses, using the default contest format.')
            format = DefaultContestFormat(contest, None)

        for participation in participations:
            participation.start = get_start(participation)
            format.update_participation(participation)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0085_contest_registration_data'),
        ('judge', '0083_extended_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='format_config',
            field=jsonfield.fields.JSONField(blank=True, help_text='A JSON object to serve as the configuration for the chosen contest format module. Leave empty to use None. Exact format depends on the contest format selected.', null=True, verbose_name='contest format configuration'),
        ),
        migrations.AddField(
            model_name='contest',
            name='format_name',
            field=models.CharField(choices=[(b'bonuses', 'Bonuses'), (b'default', 'Default')], default=b'default', help_text='The contest format module to use.', max_length=32, verbose_name='contest format'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='format_data',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='contest format specific data'),
        ),
        migrations.RunPython(contest_format_config, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='contest',
            name='first_submission_bonus',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='time_bonus',
        ),
    ]
