# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 17:33
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0085_submission_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_contest_account',
            field=models.BooleanField(default=False, help_text='If set, this account is an external user, and has extra restrictions.', verbose_name='external user'),
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_contest_account',
            new_name='is_external_user',
        ),
    ]
