# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-10 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0085_contest_registration_data'),
        ('judge', '0082_remove_profile_name'),
    ]

    operations = [
    ]
