# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0086_rating_ceiling'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='hide_problem_authors',
            field=models.BooleanField(default=False, help_text='Whether problem authors should be hidden.', verbose_name='hide problem authors'),
        ),
    ]
