# Generated by Django 2.1.12 on 2019-10-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0091_compiler_message_ansi2html'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Whether this contest is visible to external users.', verbose_name='external contest'),
        ),
    ]
