# Generated by Django 2.1.12 on 2019-10-14 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0093_permanently_hide_scoreboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestMoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('submission_count', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'contest moss result',
                'verbose_name_plural': 'contest moss results',
            },
        ),
        migrations.AddField(
            model_name='contestmoss',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moss', to='judge.Contest', verbose_name='contest'),
        ),
        migrations.AddField(
            model_name='contestmoss',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moss', to='judge.Problem', verbose_name='problem'),
        ),
        migrations.AlterUniqueTogether(
            name='contestmoss',
            unique_together={('contest', 'problem', 'language')},
        ),
    ]
