# Generated by Django 2.1.13 on 2019-11-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0095_organization_logo_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestsubmission',
            name='is_disqualified',
            field=models.BooleanField(default=False, help_text='Whether this submission is disqualified.', verbose_name='is disqualified'),
        ),
        migrations.AlterModelOptions(
            name='contestsubmission',
            options={'permissions': (('disqualify_submissions', 'Disqualify submissions'),), 'verbose_name': 'contest submission', 'verbose_name_plural': 'contest submissions'},
        ),
        migrations.AlterField(
            model_name='contestsubmission',
            name='is_disqualified',
            field=models.BooleanField(default=False, help_text='Whether this submission is disqualified.', verbose_name='is disqualified'),
        ),
    ]
