# Generated by Django 2.2.11 on 2020-03-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0098_registration_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='view_contest_scoreboard',
            field=models.ManyToManyField(blank=True, help_text='These users will be able to view the scoreboard.', related_name='view_contest_scoreboard', to='judge.Profile', verbose_name='view contest scoreboard'),
        ),
    ]
