# Generated by Django 2.2.10 on 2020-03-18 20:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations

import judge.models.profile


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0097_participation_is_disqualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_token',
            field=judge.models.profile.EncryptedNullCharField(blank=True, help_text='32 character base32-encoded API access token', max_length=32, null=True, validators=[django.core.validators.RegexValidator('^$|^[a-z2-9]{32}$', 'API token must be empty or base32')], verbose_name='API token'),
        ),
    ]
