# Generated by Django 2.2.6 on 2019-11-26 16:53

import jsonfield.fields
from django.db import migrations


def convert_json(apps, schema_editor):
    ContestRegistration = apps.get_model('judge', 'ContestRegistration')
    objs = []
    for registration in ContestRegistration.objects.all():
        if registration.data:
            registration.data = registration.data.replace("u'", '"').replace("'", '"')
        else:
            registration.data = None
        objs.append(registration)

    ContestRegistration.objects.bulk_update(objs, ['data'], batch_size=2000)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0097_participation_is_disqualified'),
    ]

    operations = [
        migrations.RunPython(convert_json, migrations.RunPython.noop, atomic=True),
        migrations.AlterField(
            model_name='contestregistration',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='user registration data'),
        ),
    ]
