# Generated by Django 2.2.10 on 2020-03-18 23:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0098_auto_20200318_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='api_token',
            field=models.CharField(blank=True, help_text='32 character base32-encoded API access token', max_length=32, null=True, validators=[django.core.validators.RegexValidator('^$|^[a-z2-9]{32}$', 'API token must be empty or base32')], verbose_name='API token'),
        ),
    ]
