# Generated by Django 2.2.11 on 2020-03-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0100_contest_visiblity_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='judged_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='submission judge time'),
        ),
    ]
