# Generated by Django 2.2.12 on 2020-04-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0102_api_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('see_private_problem', 'See hidden problems'), ('see_organization_problem', 'See organization-private problems'), ('edit_own_problem', 'Edit own problems'), ('edit_all_problem', 'Edit all problems'), ('edit_public_problem', 'Edit public not organization-private problems'), ('edit_organization_problem', 'Edit public organization-private problems'), ('clone_problem', 'Clone problem'), ('change_public_visibility', 'Change is_public field'), ('change_manually_managed', 'Change is_manually_managed field')), 'verbose_name': 'problem', 'verbose_name_plural': 'problems'},
        ),
    ]
