# Generated by Django 2.2.12 on 2020-05-04 13:46

from django.db import migrations, models

import judge.models.contest


def zero_to_none(apps, schema_editor):
    ContestProblem = apps.get_model('judge', 'ContestProblem')
    ContestProblem.objects.filter(max_submissions=0).update(max_submissions=None)


def none_to_zero(apps, schema_editor):
    ContestProblem = apps.get_model('judge', 'ContestProblem')
    ContestProblem.objects.filter(max_submissions=None).update(max_submissions=0)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0103_contest_participation_tiebreak_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestproblem',
            name='max_submissions',
            field=models.IntegerField(blank=True, default=None, help_text='Maximum number of submissions for this problem, or leave blank for no limit.', null=True, validators=[judge.models.contest.MinValueOrNoneValidator(1, "Why include a problem you can't submit to?")]),
        ),
        migrations.RunPython(zero_to_none, none_to_zero, atomic=True),
    ]
