# Generated by Django 2.2.12 on 2020-05-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0106_partially_hide_scoreboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='data_last_downloaded',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last data download time'),
        ),
    ]
