# Generated by Django 2.2.6 on 2020-05-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0106_user_data_download'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('see_private_problem', 'See hidden problems'), ('edit_own_problem', 'Edit own problems'), ('edit_all_problem', 'Edit all problems'), ('edit_public_problem', 'Edit all public problems'), ('clone_problem', 'Clone problem'), ('change_public_visibility', 'Change is_public field'), ('change_manually_managed', 'Change is_manually_managed field'), ('see_organization_problem', 'See organization-private problems')), 'verbose_name': 'problem', 'verbose_name_plural': 'problems'},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='is_restricted',
        ),
    ]
