# Generated by Django 2.2.12 on 2020-06-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0107_submission_lock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('see_private_problem', 'See hidden problems'), ('edit_own_problem', 'Edit own problems'), ('edit_all_problem', 'Edit all problems'), ('edit_public_problem', 'Edit all public problems'), ('problem_full_markup', 'Edit problems with full markup'), ('clone_problem', 'Clone problem'), ('change_public_visibility', 'Change is_public field'), ('change_manually_managed', 'Change is_manually_managed field'), ('see_organization_problem', 'See organization-private problems')), 'verbose_name': 'problem', 'verbose_name_plural': 'problems'},
        ),
        migrations.AddField(
            model_name='problem',
            name='is_full_markup',
            field=models.BooleanField(default=False, verbose_name='allow full markdown access'),
        ),
    ]
