# Generated by Django 2.2.12 on 2020-08-01 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0109_scratch_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peg_user', to='judge.Profile')),
                ('merge_into', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='peg_merge_into', to='judge.Profile')),
            ],
        ),
    ]
