# Generated by Django 2.2.12 on 2020-07-23 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('judge', '0109_scratch_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEGUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peg_merge_user', to='judge.Profile', verbose_name='user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peg_user', to='judge.Profile', verbose_name='user')),
            ],
        ),
    ]
