# Generated by Django 2.2.15 on 2020-08-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0109_scratch_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestproblem',
            name='output_prefix_override',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='output prefix length override'),
        ),
    ]
