# Generated by Django 2.2.19 on 2021-04-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0113_contest_decimal_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='partially_hide_scoreboard',
            field=models.BooleanField(default=False, help_text="Whether the scoreboard is hidden until the user's contest window ends.", verbose_name='Partially hide scoreboard'),
        ),
    ]
