# Generated by Django 2.2.19 on 2021-04-05 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0115_contest_scoreboard_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='hide_scoreboard',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='partially_hide_scoreboard',
        ),
    ]
