# Generated by Django 2.2.13 on 2021-04-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0115_contest_scoreboard_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='organizers',
            field=models.ManyToManyField(help_text='These users will be able to edit the contest.', related_name='_contest_authors_+', to='judge.Profile'),
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='organizers',
            new_name='authors',
        ),
        migrations.AddField(
            model_name='contest',
            name='curators',
            field=models.ManyToManyField(blank=True, help_text='These users will be able to edit the contest, but will not be listed as authors.', related_name='_contest_curators_+', to='judge.Profile'),
        ),
        migrations.AddField(
            model_name='contest',
            name='testers',
            field=models.ManyToManyField(blank=True, help_text='These users will be able to view the contest, but not edit it.', related_name='_contest_testers_+', to='judge.Profile'),
        ),
    ]
