# Generated by Django 2.2.17 on 2021-04-27 14:46

from django.db import migrations, models
from django.db.models import F


def convert_to_datetime(apps, schema_editor):
    Submission = apps.get_model('judge', 'Submission')

    Submission.objects.filter(was_rejudged=True).update(rejudged_date=F('judged_date'))


def convert_to_boolean(apps, schema_editor):
    Submission = apps.get_model('judge', 'Submission')

    Submission.objects.filter(rejudged_date__isnull=False).update(was_rejudged=True)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0117_remove_private_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='rejudged_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last rejudge date by admin'),
        ),
        migrations.RunPython(convert_to_datetime, convert_to_boolean, atomic=True),
        migrations.RemoveField(
            model_name='submission',
            name='was_rejudged',
        ),
    ]
