# Generated by Django 2.2.24 on 2021-08-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0121_per_problem_sub_access_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username_display_override',
            field=models.CharField(blank=True, max_length=100, verbose_name='display name override', help_text='name displayed in place of username'),
        ),
    ]
