# Generated by Django 2.2.24 on 2021-10-31 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0124_contest_show_short_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='class_required',
            field=models.BooleanField(default=False, help_text='whether members are compelled to select a class when joining', verbose_name='class membership required'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='class name')),
                ('slug', models.SlugField(help_text='class name shown in URLs', max_length=128, verbose_name='class slug')),
                ('description', models.TextField(blank=True, verbose_name='class description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is class active')),
                ('access_code', models.CharField(blank=True, help_text='student access code', max_length=7, null=True, verbose_name='access code')),
                ('admins', models.ManyToManyField(help_text='those who can approve membership to this class', related_name='class_admin_of', to='judge.Profile', verbose_name='administrators')),
                ('members', models.ManyToManyField(blank=True, related_name='classes', related_query_name='class', to='judge.Profile', verbose_name='members')),
                ('organization', models.ForeignKey(help_text='the organization that this class belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='classes', related_query_name='class', to='judge.Organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contest',
            name='classes',
            field=models.ManyToManyField(blank=True, help_text='If organization private, only these classes may see the contest', to='judge.Class', verbose_name='classes'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(condition=models.Q(is_active=True), fields=('name',), name='unique_active_name'),
        ),
        migrations.AddField(
            model_name='organizationrequest',
            name='request_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.Class', verbose_name='class'),
        ),
    ]
