# Generated by hand on 2021-12-15

from django.db import migrations


def sync_private_booleans(apps, schema_editor):
    Problem = apps.get_model('judge', 'Problem')
    Contest = apps.get_model('judge', 'Contest')
    db_alias = schema_editor.connection.alias

    for problem in Problem.objects.using(db_alias).all():
        if not problem.is_organization_private:
            problem.organizations.clear()
        elif not problem.organizations.exists():
            problem.is_organization_private = False
            problem.save()

    for contest in Contest.objects.using(db_alias).all():
        if not contest.is_private:
            contest.private_contestants.clear()
        elif not contest.private_contestants.exists():
            contest.is_private = False
            contest.save()
        if not contest.is_organization_private:
            contest.organizations.clear()
        elif not contest.organizations.exists():
            contest.is_organization_private = False
            contest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0125_organization_classes'),
    ]

    operations = [
        migrations.RunPython(sync_private_booleans, migrations.RunPython.noop),
    ]
