# Generated by Django 2.2.27 on 2022-02-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0127_tester_see_scoreboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='join_organizations',
            field=models.ManyToManyField(blank=True, help_text='If non-empty, only these organizations may join the contest', related_name='join_only_contests', to='judge.Organization', verbose_name='join organizations'),
        ),
        migrations.AddField(
            model_name='contest',
            name='limit_join_organizations',
            field=models.BooleanField(default=False, verbose_name='limit organizations that can join'),
        ),
    ]
