# Generated by Django 2.2.27 on 2022-02-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0128_limit_join_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='tester_see_submissions',
            field=models.BooleanField(default=False, help_text='If testers can see in-contest submissions.', verbose_name='testers see submissions'),
        ),
        migrations.AddField(
            model_name='contest',
            name='view_contest_submissions',
            field=models.ManyToManyField(blank=True, help_text='These users will be able to see in-contest submissions.', related_name='view_contest_submissions', to='judge.Profile', verbose_name='can see contest submissions'),
        ),
    ]
