# Generated by Django 2.2.27 on 2022-02-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0129_see_scoreboard_subs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': (('edit_all_post', 'Edit all posts'), ('change_post_visibility', 'Edit post visibility')), 'verbose_name': 'blog post', 'verbose_name_plural': 'blog posts'},
        ),
    ]
