# Generated by Django 2.2.27 on 2022-03-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0131_spectate_contests'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='implicit_problem_perms',
            field=models.BooleanField(default=False, help_text='If contest personnel have implicit view permissions on contest problems', verbose_name='implicit problem permissions'),
        ),
    ]
