# Generated by Django 3.2.16 on 2022-12-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0133_add_binary_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='hints',
            field=models.CharField(blank=True, choices=[('unicode', 'Unicode'), ('none', 'NONE')], max_length=10, verbose_name='hints'),
        ),
    ]
