# Generated by Django 3.2.16 on 2023-02-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0138_dark_ace_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='performance_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='problem_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_unlisted', '-performance_points'], name='judge_profi_is_unli_1410d8_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_unlisted', '-rating'], name='judge_profi_is_unli_bcf16a_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_unlisted', '-problem_count'], name='judge_profi_is_unli_171bf3_idx'),
        ),
    ]
