# Generated by Django 3.2.23 on 2024-01-02 08:20

from django.db import migrations, models
import judge.models.problem


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0144_submission_index_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='authorship_name',
            field=models.CharField(blank=True, help_text="Use it for attribution purposes, the original author's name will be added at the end of the problem.", max_length=100, verbose_name="author's name"),
        ),
        migrations.AddField(
            model_name='problem',
            name='authorship_uri',
            field=models.URLField(blank=True, max_length=255, verbose_name="author's URI"),
        ),        
    ]
