# Generated by Django 4.2.17 on 2025-04-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0149_add_organization_private_problems_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'permissions': (('see_private_contest', 'See private contests'), ('edit_own_contest', 'Edit own contests'), ('edit_all_contest', 'Edit all contests'), ('clone_contest', 'Clone contest'), ('moss_contest', 'MOSS contest'), ('contest_rating', 'Rate contests'), ('contest_access_code', 'Contest access codes'), ('create_private_contest', 'Create private contests'), ('change_contest_visibility', 'Change contest visibility'), ('contest_problem_label', 'Edit contest problem label script'), ('lock_contest', 'Change lock status of contest'), ('override_performance_ceiling', 'Override performance ceiling of contest')), 'verbose_name': 'contest', 'verbose_name_plural': 'contests'},
        ),
        migrations.AddField(
            model_name='contest',
            name='performance_ceiling_override',
            field=models.IntegerField(blank=True, help_text="Overrides the performance_ceiling parameter used in computing ratings. Do not modify unless you know what you're doing!", null=True, verbose_name='performance ceiling override'),
        ),
    ]
