# Generated by Django 4.2.19 on 2025-03-25 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0150_add_performance_ceiling'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationbar',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.permission', verbose_name='permission'),
        ),
    ]
