# Generated by Django 4.2.17 on 2025-03-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0150_add_performance_ceiling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={
                'permissions': (
                    ('abort_any_submission', 'Abort any submission'),
                    ('rejudge_submission', 'Rejudge the submission'),
                    ('rejudge_submission_lot', 'Rejudge a lot of submissions'),
                    ('spam_submission', 'Submit without limit'),
                    ('view_all_submission', 'View all submission'),
                    ('resubmit_other', "Resubmit others' submission"),
                    ('lock_submission', 'Change lock status of submission'),
                    ('archive_submission', 'Archive any submission'),
                ),
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='is archived'),
        ),
    ]
