# Generated by Django 4.2.27 on 2025-12-20 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0151_submission_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('test_site', 'Shows in-progress development stuff'), ('totp', 'Edit TOTP settings'), ('deactivate_users', 'Deactivate users')), 'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
    ]
