# Generated by Django 4.2.25 on 2025-11-28 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0151_problem_view_test_cases_problem_view_tester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='template code')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.language', verbose_name='language')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='judge.problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'problem template',
                'verbose_name_plural': 'problem templates',
                'unique_together': {('problem', 'language')},
            },
        ),
    ]
