# Generated by Django 5.0.14 on 2025-08-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0151_alter_contest_private_contestants_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='class',
            name='unique_active_name',
        ),
    ]
