# Generated by Django 4.2.27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0152_deactivate_user_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemdata',
            name='output_limit',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(104857600)], verbose_name='output limit length'),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='output_limit',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(104857600)], verbose_name='output limit length'),
        ),
    ]
