name: dmoj-merge
on:
  schedule:
    # Mondays at noon
    - cron: '0 12 * * 1'
  repository_dispatch:
    types: [manual-run]

jobs:
  dmoj-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: mcpt/fork-sync@v1.1.7-mcpt
      name: Create pull request
      with:
        github_token: ${{ secrets.TOKEN }}
        owner: dmoj
        base: master
        head: master
        pr_title: Merge DMOJ into DMOJ-merge
        pr_message: This is an automated pull request to merge upstream changes into master.
