name: makemessages
# TODO: restrict to master
on: [push]
jobs:
  makemessages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Checkout submodules
      run: |
        git submodule init
        git submodule update
    - name: Install requirements
      run: pip install -r requirements.txt && pip install pymysql
    - name: Collect localizable strings
      run: |
        echo "STATIC_ROOT = '/tmp'" > dmoj/local_settings.py
        python manage.py makemessages -l en -e py,html,txt
        python manage.py makemessages -l en -d djangojs
