name: DMOJ Site
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install flake8
      run: pip install flake8 flake8-import-order flake8-future-import flake8-commas flake8-logging-format
    - name: Lint with flake8
      run: |
        flake8 --version
        flake8
